export type JobData = {
    _id: string,
    jobTitle: string,
    jobType: string,
    jobDuration: string,
    isThereSalary: boolean,
    jobSalary: string,
    jobSalaryPer: string,
    country: string,
    state: string,
    city: string,
    jobPhoto: string,
    jobFormLink: string,
    wantEasyApply: boolean,
    isThereContact: boolean,
    currency: string,
    contactPhoto: string,
    contactName: string,
    contactEmail: string,
    contactNumber: string,
    theOtherJobDuration: string,
    emailRef: string,
    description: string,
    createdAt: Date,
    updatedAt: Date,
    __v: number,
}